-- DO NOT RUN THIS SQL IN PRODUCTION! THIS IS HERE FOR DEVELOPMENT PURPOSES ONLY!
CREATE DATABASE IF NOT EXISTS `wp_traits`;
GRANT ALL ON `wp_traits`.* TO 'wp_traits'@'localhost' IDENTIFIED BY 'password';